name: untitled4
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  open_file: ^3.3.2
  cupertino_icons: ^1.0.2
  date_field: ^3.0.5
  intl: ^0.18.1
  doc_widget: ^0.4.0
  csc_picker: ^0.2.7
  image_picker: ^1.0.4
  firebase_messaging: ^14.7.5
  smooth_page_indicator: ^1.1.0
  emoji_picker_flutter: ^1.6.2
  readmore: ^2.2.0
  grouped_list: ^5.1.2
  dropdown_button2: ^2.3.9
  multiselect_nested: ^1.1.0
  multi_select_flutter: ^4.1.3
  intl_phone_field: ^3.2.0
  http: ^1.1.0
  multipart: ^0.1.2
  logger: ^2.0.2+1
  flutter_secure_storage: ^9.0.0
  line_icons: ^2.0.3
  animate_do: ^3.1.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  custom_navigation_bar: ^0.8.2
  file_picker: ^6.1.1
  dio: ^5.3.3
  url_launcher: ^6.0.6
  firebase_core: ^2.23.0
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  firebase_analytics: ^10.7.2
  flutter_local_notifications: ^16.2.0
  mailer: ^6.0.1
  
  
 
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/profpic.png
    - images/TLL.png
    - images/girlSit.jpeg
    - images/loginimg.png
    - images/workTime.jpeg
    - images/cooom.jpeg
    - images/logggin.jpeg
    - images/forgotPass.jpeg
    - images/DoneNewPass.jpeg
    - images/codeverific.jpeg
    - images/addnewpass.jpeg
    - images/sssign.jpeg
    - images/signimg.png
    - images/students.png
    - images/c9ommm.jpeg
    - images/stuuu.jpeg
    - images/comp.png
    - images/WelcomePP.png
    - images/blankimg.PNG
    - images/stuORcom.png
    - images/drawer.png
    - images/omar.jpg
    - images/Harri.jpeg
    - images/hr.jpeg
    - images/Sponser.png
    - images/asal.jpeg
    - images/asal-post.jpeg
    - images/foothill.jpeg
    - images/studentBoy.jpeg
    - images/studentGirl.jpeg
    - images/foothill-post.jpeg
    - images/groups.jpeg
    - images/harri-post22.png
    - images/g4.jpeg
    - images/g4LIST.jpeg
    - images/teamGroups (1).jpeg
    - images/teamGroups (2).jpeg
    - images/teamGroups (3).jpeg
    - images/teamGroups (4).jpeg
    - images/gharri.jpg
    - images/nogroups.jpg
    - images/noreports.jpg
    - images/nogroups.jpeg
    - images/noreports.jpeg
    - images/najah.jpg
    - images/contact.jpeg
    - images/educational.jpeg
    - images/projects.jpeg
    - images/training.jpeg
    - images/toDolist.jpeg
    - images/progineer.jpg
    - images/asal.jpeg
    - images/TLp.png

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
